apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitty
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kitty
  template:
    metadata:
      labels:
        app: kitty
    spec:
      containers:
        - name: kitty
          image: 058625519174.dkr.ecr.us-west-2.amazonaws.com/kitty:latest
          ports:
            - containerPort: 80
