# works
# assumptions are you have a namespace and a deployment already created
#
# build, push, sign, and deploy to the cluster... 
# todo: would like to get kyverno or gatekeeper working properly in here at some point to verify the signature before deploying
#
on:
  #pull_request:
  #  paths:
  #  - app/**
  #push:
  #  paths:
  #  - app/**
  #  branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
  #  - main            # triggers on pushes that contain changes in master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


name: OhBoy

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-west-2
  ECR_REPOSITORY: kitty
  IMAGE_TAG: latest
   
jobs:
  build:
    
    name: Do a bunch of stuff
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Deploy
      uses: safe2008/eks-actions@v0.0.4
      env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          cluster_name: kitty
          #ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
          args: |
            kubectl set image deployment/kitty2 -n kitty
            
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
      
    - name: Check Deployment
      uses: safe2008/eks-actions@v0.0.4     
      with:
          args: |
            kubectl rollout status deployment/kitty2 -n kitty
